CREATE PROCEDURE [dbo].[usp_GetCustomerOrder]
(
	@Value varchar(13)
)
AS
BEGIN
	SELECT TOP 20 C.ID, C.NAME, P.NUMBER, 
A.CEP, A.STREET, A.DISTRICT, CI.NAME AS CITY   FROM CUSTOMER C INNER JOIN CUSTOMERANDRESS CA ON C.ID = CA.CUSTOMERID
INNER JOIN ANDRESS A ON A.ID = CA.ANDRESSID AND CA.MAIN = 1
LEFT JOIN CITY CI ON CI.ID = A.CITYID
INNER JOIN CUSTOMERPHONE CP ON CP.CUSTOMERID = C.ID
INNER JOIN PHONE P ON P.ID = CP.PHONEID
WHERE CAST(P.Number AS VARCHAR(13)) LIKE   @value +'%'

END

